trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  imageName: 'pipelines-dotnet-core-docker'
  tag: '(Build.BuildId)'

steps:
- task: Docker@2
  displayName: Build an image
  inputs:
    repository: $(imageName)
    command: build
    Dockerfile: Dockerfile
    tags: |
      $(tag)

- task: Docker@2
  displayName: Push image
  inputs:
    containerRegistry: |
      innovation-acr
    repository: $(imageName)
    command: push
    tags: |
      $(tag)
