trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  imageName: 'pipelines-dotnet-core-docker'

steps:
- task: Docker@2
  displayName: Build an image
  inputs:
    repository: $(imageName)
    command: build
    Dockerfile: Dockerfile

- task: Docker@2
  displayName: Push image
  inputs:
    containerRegistry: |
      $(ACR)
    repository: $(imageName)
    command: push
    tags: |
      aspnetcoreapp31
      v2